In [14]:
import numpy as np 

# Basics of NumPy

# 1. Array Creation : 1. Using Lists & Tuples

In [12]:
# Creating single dimensional array using numpy
myarr=np.array([1,2,3] , np.int8) # using np.int8, int64 types command , we can decide the max no of bits possible for a number 
myarr

array([1, 2, 3], dtype=int8)

In [3]:
# Creating two dimansional array 

myarr1 = np.array([[4,5,6]] , np.int64)
myarr1

array([[4, 5, 6]], dtype=int64)

In [4]:
myarr1[0,1] # accesing element of zeroth row &  1st column

5

In [5]:
myarr[1] # accesing element from one dimensional array having index==1

2

In [6]:
myarr.dtype # command to get max possible no of bits for given array

dtype('int8')

In [7]:
myarr1[0,2]=12 # To change the ekement at desired index
myarr1

array([[ 4,  5, 12]], dtype=int64)

# Array Creation : 2. Conversion from other python structures 

In [8]:
hash = np.array([[1,2,3],[4,5,6],[7,8,9]])
hash

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
hash.dtype # to get max no of bit it can intake for each value or element

dtype('int32')

In [10]:
hash.shape # to get the order of an array

(3, 3)

In [11]:
hash.size # to get total possible no of elements in an array

9

In [12]:
np.array({1,3,5}) # To get dtype=object

array({1, 3, 5}, dtype=object)

# Array Creation : 3. Intrinsic Numpy array creation object (eg. zeros,ones,arange,etc)

In [13]:
# Using zeros function
hash1 = np.zeros([3,6]) # To get an array of m by n order whose each initial element is zero
hash1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
# Using arange function
hash2 = np.arange(15) # To get an array containing its initial value as its index for each array element 
hash2 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
# Using identity function
hash3 = np.identity(5) # To get an identity matrix or two dimensional array of n by n order 
hash3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
# using linspace function
hash4 = np.linspace(1,50,10) # it generates an array starting from 1 terminating on 50 & having 10 equispaced values
hash4

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [17]:
# Using empty function
hash5 = np.empty((4,6)) # It generates any random value array
hash5

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
# Using empty_like function
hash6 = np.empty_like(hash4)
hash6

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [19]:
# array reshape
hash7 = np.arange(99)
hash7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [20]:
# Continuing array reshape
hash8 = hash7.reshape(3,33)
hash8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [21]:
# To remove/undo the shape use ravel
hash9 = hash8.ravel()
hash9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# 2. Playing with axis & attributes

In [22]:
hash10 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # declaring an array

In [23]:
hash11 = np.array(hash10) # passing a parameter to an array
hash11

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
hash11.sum(axis=0) # calulating sum of axis=0 elemnents i.e column 1,2,3

array([12, 15, 18])

In [25]:
hash11.sum(axis=1) # calculating sum of axis=1 elements i.e row 1,2,3

array([ 6, 15, 24])

In [26]:
hash11.T # to get transpose of a matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [27]:
hash11.flat # to get an iterator to use it for special loop purpose

In [28]:
for values in hash11.flat : # to get all the elements of an array or to use array value for loop purpose
    print(values)

1
2
3
4
5
6
7
8
9


In [29]:
hash11.ndim # to get no of dimensions

2

In [30]:
hash11.size # to get total no of elements

9

In [31]:
hash11.nbytes # total bytes consumed

36

In [32]:
hash12 = np.array([1,20,30,4,6,0,24,2])
hash12.argmax() # to get the index of largest value in given array

2

In [33]:
hash12.argmin() # to get index of smallest value in given array

5

In [34]:
hash12.argsort() # to get the index order of the elements if arranged in increasing manner

array([5, 0, 7, 3, 4, 1, 6, 2], dtype=int64)

In [35]:
hash11

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
hash11.argmin()

0

In [37]:
hash11.argmax()

8

In [38]:
hash11.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [39]:
hash11.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [40]:
hash11.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [41]:
hash11.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [42]:
hash11.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
hash11.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [44]:
hash13 = np.array([[1,12,13],[2,23,24],[3,4,13]])
hash13

array([[ 1, 12, 13],
       [ 2, 23, 24],
       [ 3,  4, 13]])

In [45]:
hash14 = ([[1,3,5],
          [7,9,11],
          [13,15,17]])

In [46]:
hash13 + hash14 # Addition of arrays

array([[ 2, 15, 18],
       [ 9, 32, 35],
       [16, 19, 30]])

In [47]:
[23,34,12] + [46,52,93] # merging two arrays ( array addition is not possible when we declare it in list format)

[23, 34, 12, 46, 52, 93]

In [48]:
hash13 * hash14 # multiplication of arrays

array([[  1,  36,  65],
       [ 14, 207, 264],
       [ 39,  60, 221]])

In [49]:
np.sqrt(hash14) # To get element wise square root in resoective array form

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [50]:
hash15 = hash13 + hash14
hash15

array([[ 2, 15, 18],
       [ 9, 32, 35],
       [16, 19, 30]])

In [51]:
np.where(hash15 > 9) # to get the index of the element whos value is greater than certain number

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 1, 2, 0, 1, 2], dtype=int64))

In [52]:
np.count_nonzero(hash15) # to get total no of nonzero elements

9

In [53]:
np.nonzero(hash15) # to get index of nonzero elements

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [54]:
hash15[1,2] = 0  # changing value of certain element

In [55]:
hash15 # again declaring an array with updated values

array([[ 2, 15, 18],
       [ 9, 32,  0],
       [16, 19, 30]])

In [56]:
np.nonzero(hash15) # the index having zero value is missing

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [57]:
import sys

# Testing memory requirments as well as understanding benfits of using numpy

In [58]:
py_array = ([1,2,3]) # declaring python array

In [59]:
np_array = np.array(py_array) # declaring an array using numpy

In [60]:
sys.getsizeof(1) # memory occupied by 1 element of py_array

28

In [61]:
sys.getsizeof(1)*len(py_array) # total memory occupied by all the elements of py_array 

84

In [62]:
np_array.itemsize*np_array.size # total memory occupied by array using numpy

12

In [63]:
np_array.tolist() # to convert numoy array into python list

[1, 2, 3]

In [19]:
import array as arr
hash1921 = ([1,2,3])
hash1921

[1, 2, 3]